Select
Sivegy/Training pull request #8
Opened 2022-11-14 19:35 UTC by Sivegy

Check my task please

2022-11-15 08:57 UTC, NOSkcjn commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +SELECT * FROM Clients WHERE Rating IS NULL
нужно только ФИО, причем полное вывести в одном поле

2022-11-15 08:59 UTC, NOSkcjn commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +ORDER BY Cars.StarsCount DESC
а нужен ли тут Group by ?

2022-11-15 09:00 UTC, NOSkcjn commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +ORDER BY Rating ASC
то же самое, что в двух комментах выше

2022-11-15 09:04 UTC, NOSkcjn commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +WHERE Cars.ReleaseDate <= '14.01.2020'
тут жестко задана дата. надо вычитать из текущей

2022-11-15 09:07 UTC, NOSkcjn commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +ORDER BY Cars.StarsCount DESC
попробуй добавить 2 и более автомобиля с одной моделью и посмотреть какая из них будет тут выводиться

2022-11-15 09:10 UTC, NOSkcjn commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +5. Вывести марку автомобиля, которая присутствует в автопарке больше всех (Марка)
тем временем машина, которой всего одна модель, но которых полно в автопарке, такая:
![image](https://user-images.githubusercontent.com/25517410/201877801-b890db61-204b-4c10-ab75-5bd52640a8ab.png)

2022-11-15 09:12 UTC, NOSkcjn commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +ORDER BY Rating ASC
и клиентов без рейтинга сюда не выводить

2022-11-15 09:13 UTC, NOSkcjn requested changes
.

2022-11-15 10:47 UTC, Sivegy commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +SELECT * FROM Clients WHERE Rating IS NULL
ok

2022-11-15 10:47 UTC, Sivegy commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +ORDER BY Cars.StarsCount DESC
без Group by не работает

2022-11-15 11:16 UTC, Sivegy commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +ORDER BY Rating ASC
ok

2022-11-15 11:22 UTC, Sivegy commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +5. Вывести марку автомобиля, которая присутствует в автопарке больше всех (Марка)
ну они будут добавляться в таблицу Models и все равно верно считаться

2022-11-15 11:23 UTC, Sivegy commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +5. Вывести марку автомобиля, которая присутствует в автопарке больше всех (Марка)
![Models](https://user-images.githubusercontent.com/116363747/201907645-7d08f49e-c8a6-4b09-96c2-dd43bb4d41aa.png)

2022-11-15 11:23 UTC, Sivegy commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +5. Вывести марку автомобиля, которая присутствует в автопарке больше всех (Марка)
как здесь BMW M5 дублируется

2022-11-15 15:14 UTC, Sivegy commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +WHERE Cars.ReleaseDate <= '14.01.2020'
ок

2022-11-15 15:15 UTC, Sivegy commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +    FETCH NEXT 1 ROWS ONLY
поменяю на TOP

2022-11-15 15:15 UTC, Sivegy commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +5. Вывести марку автомобиля, которая присутствует в автопарке больше всех (Марка)
короче я не понял что не так

2022-11-15 15:15 UTC, Sivegy commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +ORDER BY Cars.StarsCount DESC
ок

2022-11-16 10:41 UTC, NOSkcjn commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +SELECT TOP 5 FirstName, Surname, Patronymic, Rating FROM Clients
тут тоже Concat должен был быть, но ладно)

2022-11-16 14:23 UTC, Sivegy commented on tasks/DataBase carsharing/SQL SELECT/SQL SELECT.txt
> +SELECT TOP 5 FirstName, Surname, Patronymic, Rating FROM Clients
исправил

2022-11-16 20:31 UTC, NOSkcjn approved these changes

2022-11-16 21:07 UTC, merged